name: Build, Push and Deploy to AKS

on:
  push:
    branches:
      - Murali_New_Branch_for_Test

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/muraliportfolio:latest

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install kubelogin for AKS AAD auth
      - name: Install kubelogin
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext-base unzip
          curl -L https://github.com/Azure/kubelogin/releases/download/v0.1.7/kubelogin-linux-amd64.zip -o /tmp/kubelogin.zip
          unzip /tmp/kubelogin.zip -d /tmp/kubelogin
          sudo install /tmp/kubelogin/kubelogin /usr/local/bin/kubelogin
          chmod +x /usr/local/bin/kubelogin
          kubelogin --version

      # Connect to AKS
      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      # Deploy to AKS
      - name: Deploy Application
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/muraliportfolio:latest
        run: |
          envsubst < K8s/deployment.yaml > /tmp/deployment.yaml
          kubectl apply -f /tmp/deployment.yaml
          kubectl apply -f K8s/service.yaml

      # Restart Deployment
      - name: Restart Deployment
        run: |
          kubectl rollout restart deployment/muraliportfolio

      # Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc

